FROM node:22-alpine3.19 AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --omit=dev
COPY ./src ./src
COPY ./videos ./videos

FROM node:22-alpine3.19
WORKDIR /usr/src/app
COPY --from=build /usr/src/app /usr/src/app
CMD ["npm", "start"]